spring:
  application:
    name: BatchYDEApp
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    url: jdbc:h2:file:c:\ydeapp\db\db_cartographie
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: never
  batch:
    initialize-schema: always
    job:
      enabled: false

logging:
  level:
    org.yde.ydeapp: error
    org.springframework: info
ydeapp:
  dir: c:\ydeapp
