spring:
  application:
    name: YDEAppBatch
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${YDE_DB_CARTOGRAPHIE_SERVICE_HOST}:${YDE_DB_CARTOGRAPHIE_SERVICE_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialization-mode: never
  batch:
    initialize-schema: always
    job:
      enabled: false

logging:
  level:
    org.yde.ydeapp: debug
    org.springframework.batch: info

ydeapp:
  dir: ${YDE_STORE}
