spring:
  application:
    name: YDEApp
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${YDE_DB_CARTOGRAPHIE_SERVICE_HOST}:${YDE_DB_CARTOGRAPHIE_SERVICE_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      login-timeout: 30000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 9090
logging:
  level:
    org.yde.ydeapp: error
    org.springframework: error
ydeapp:
  dir: ${YDE_STORE}
  client: http://localhost:4201
  secret: ydeapp-42-secret-of-life
