spring:
  application:
    name: YDEApp
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5436/db_cartographie
    username: yde_users
    password: yde_users
    driverClassName: org.postgresql.Driver
  batch:
    initialize-schema: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 9090
logging:
  level:
    org.yde.ydeapp: error
    org.springframework: info

